### ISSUE TITLE
source parameter

### ISSUE THREAD

**Issue by jaimebayes** [nickeubank/gis_in_r#2]
Hi Nick,

I found an error using geocode function:

> locations <- geocode(addresses, source = "google", output = "more")
> Error in geocode(addresses, source = "google", output = "more") : 
>   unused argument (source = "google")
> but, when I run it without source parameter, it works well:
> geocode(addresses)
> What could be wrong here?

 A little suggestion to your tutorial 4, you can use this:

> addresses <- read.csv("C:/RGIS4_Data/addresses_to_geocode.csv", stringsAsFactors = FALSE), 
> to avoid one line in your code, 
> addresses <- read.csv("RGIS4_Data/addresses_to_geocode.csv")
> addresses$Location <- as.character(addresses$Location)

Thanks for your tutorial, it is really good.

Jaime

**Comment by nickeubank** [comment]
Hi @jaimebayes what version of ggmap are you using? Version 2.5.2 definitely is ok with the source parameter -- from docs:

```
geocode {ggmap} R Documentation
Geocode

Description

Geocodes a location (find latitude and longitude) using either (1) the Data Science Toolkit (http://www.datasciencetoolkit.org/about) or (2) Google Maps. Note that when using Google you are agreeing to the Google Maps API Terms of Service at https://developers.google.com/maps/terms.

Usage

geocode(location, output = c("latlon", "latlona", "more", "all"),
  source = c("dsk", "google"), messaging = FALSE, sensor = FALSE,
  override_limit = FALSE, client = "", signature = "",
  nameType = c("long", "short"), data)

geocodeQueryCheck(userType = "free")
```

**Comment by jaimebayes** [comment]
Hi Nick, 
You are right, my ggmap version is 2.4, I have to update it 2.5.2.
Thanks, Jaime

**Comment by nickeubank** [comment]
@jaimebayes Great! Glad I could help! :)
