### ISSUE TITLE
Remove `@data` references

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/gis_in_r#3]
As pointed out by @edzer , don't really need to introduce users to `@` notation, or `@data` notation. Was required when I thought was required for attribute joins, but can now be removed.

**Comment by nickeubank** [comment]
Actually, need to keep -- no other way to pull out attribute table, which is too common an operation.

**Comment by edzer** [comment]
as.data.frame(x) does it, and even explains what it does.

**Comment by nickeubank** [comment]
hmm, good point. OK, updating.

**Comment by nickeubank** [comment]
@edzer How would you handle bringing back in data from an `over` command, as in the following (from `RGIS2_MergingSpatialData_part1_joins`, lines 209-213) without `@data`?

```
grants.districts <- over(grants.newproj, districts) # Get district data

# Recombine!
grants.newproj@data <- cbind(grants.newproj@data, grants.districts)
```

(thanks again for help on this! Much appreciated.)

**Comment by edzer** [comment]
`over` drops the geometry; `d <- districts[grants.newproj, ]` keeps them (from district). Try `sp::merge` to merge a `Spatial` object with a `data.frame`, based on a common ID.

**Comment by nickeubank** [comment]
So in this case I'm trying to do a spatial join, then re-integrate the information on the district in which each grant is located. 

Would you do something like convert the rownames to a column, then merge on those with sp::merge? 

Or said more broadly: 

Say I have points and polygons (say, projects and districts), and want to add information about the polygon in which each point is located to the point (so I have `data.frame` for the projects that includes the district in which they're located). 

What's the alternate code flow for re-integrating the output of `over` back into the points?

**Comment by edzer** [comment]
For individual vectors, you use 
`grants.newproj$xx <- districts[grants,newproj,]$xx` or `over(grants.newproj, distr)$xx`.
For whole data.frames, use `maptools::spCbind`

**Comment by nickeubank** [comment]
Finally completed, integrated, and uploaded to tutorial lists. Thanks @edzer !
